# Generated by Django 5.2.8 on 2026-04-30 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_fecha_expiracion_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ejercicio', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('repeticiones', models.IntegerField(default=0)),
                ('tiempo_segundos', models.FloatField(default=0.0)),
                ('precision_porcentaje', models.FloatField(default=100.0, help_text='Precisión general del ejercicio calculada por la IA')),
                ('completado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_entrenamientos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorPostural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_error', models.CharField(help_text="Ej: 'Caderas no estables', 'Rodillas dobladas', 'Codos < 90 grados'", max_length=150)),
                ('cantidad', models.IntegerField(default=1, help_text='Número de veces que ocurrió el error en la sesión')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='usuarios.historialentrenamiento')),
            ],
        ),
    ]
