# Generated by Django 5.2.8 on 2026-06-02 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_historialentrenamiento_errorpostural'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo_principal', models.CharField(blank=True, max_length=100, null=True)),
                ('experiencia_deporte', models.CharField(blank=True, max_length=50, null=True)),
                ('dias_entrenamiento', models.IntegerField(default=3)),
                ('tiene_dolor_lumbar', models.BooleanField(default=False)),
                ('tiene_lesion_menisco', models.BooleanField(default=False)),
                ('tiene_dolor_cervical', models.BooleanField(default=False)),
                ('tiene_lesion_hombro', models.BooleanField(default=False)),
                ('tiene_tendinitis', models.BooleanField(default=False)),
                ('otras_lesiones', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_clinico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
