# Generated by Django 5.2.8 on 2026-06-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_perfilclinico'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorpostural',
            name='repeticion',
            field=models.IntegerField(default=0, help_text='Número de repetición en que ocurrió el error'),
        ),
    ]
