# Generated by Django 5.2.8 on 2026-06-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_errorpostural_repeticion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilclinico',
            name='equipamiento',
            field=models.CharField(default='ninguno', help_text='Equipamiento disponible (ninguno, mancuernas, completo)', max_length=50),
        ),
    ]
