# Generated by Django 5.2.8

from django.db import migrations

def seed_plans(apps, schema_editor):
    TipoPlan = apps.get_model('suscripciones', 'TipoPlan')
    
    # Crear Gratis
    TipoPlan.objects.get_or_create(
        clave='gratis',
        defaults={
            'nombre': 'FREE_TERMINAL',
            'precio': 0.0,
            'duracion_dias': 365,
            'minutos_por_dia': 15,
            'feedback_voz': False,
            'analisis_angulos': False,
            'historial_dias': 0,
            'con_anuncios': True,
            'popular': False,
            'icono': '🆓',
            'color': 'border-white/10',
            'orden': 1
        }
    )

    # Crear Básico
    TipoPlan.objects.get_or_create(
        clave='basico',
        defaults={
            'nombre': 'BASIC_UNIT',
            'precio': 25.0,
            'duracion_dias': 30,
            'minutos_por_dia': 60,
            'feedback_voz': True,
            'analisis_angulos': False,
            'historial_dias': 7,
            'con_anuncios': True,
            'popular': True,
            'icono': '⭐',
            'color': 'border-yellow-400/20',
            'orden': 2
        }
    )

    # Crear Premium
    TipoPlan.objects.get_or_create(
        clave='premium',
        defaults={
            'nombre': 'PREMIUM_ELITE',
            'precio': 49.0,
            'duracion_dias': 30,
            'minutos_por_dia': -1,
            'feedback_voz': True,
            'analisis_angulos': True,
            'historial_dias': -1,
            'con_anuncios': False,
            'popular': False,
            'icono': '👑',
            'color': 'border-yellow-400',
            'orden': 3
        }
    )

def remove_plans(apps, schema_editor):
    TipoPlan = apps.get_model('suscripciones', 'TipoPlan')
    TipoPlan.objects.filter(clave__in=['gratis', 'basico', 'premium']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('suscripciones', '0003_metodopago_tipoplan_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_plans, remove_plans),
    ]
